import os
import time

import streamlit as st
from aiortc.contrib.media import MediaRecorder
from streamlit_webrtc import WebRtcMode, webrtc_streamer

from ai_tutor import AITutor
import verify
from whisper_model import WhisperModel

st.set_page_config(page_title="AI Tutor")
st.title("AI Tutor")


def display_verification_report(report: dict):
    st.header("AI STUDENT UNDERSTANDING VERIFICATION REPORT")

    st.subheader("Transcript")
    st.write(report.get("transcript", ""))

    st.subheader("Understanding Score")
    st.metric("Score", f"{report.get('understanding_score', 0.0):.2f}%")
    st.write(
        "Understanding Score is generated by the AUVA algorithm. "
        "It combines semantic similarity, concept coverage, attention, and speech confidence, "
        "with deductions for knowledge gaps and misconceptions."
    )

    st.subheader("Semantic Similarity")
    semantic_block = report.get("semantic", {})
    st.metric("Score", f"{semantic_block.get('score', 0.0):.2f}%")
    st.write(semantic_block.get("explanation", ""))

    st.subheader("Concept Coverage")
    concept_block = report.get("concept", {})
    st.metric(
        "Coverage",
        f"{concept_block.get('detected_count', 0)} / {concept_block.get('total', 0)} ({concept_block.get('coverage', 0.0):.2f}%)",
    )
    if concept_block.get("detected"):
        st.write("Detected Concepts:")
        for concept_text in concept_block.get("detected", []):
            st.write(f"✓ {concept_text}")
    st.write(concept_block.get("explanation", ""))

    st.subheader("Knowledge Gap")
    if concept_block.get("missing"):
        for missing_text in concept_block.get("missing", []):
            st.write(f"- {missing_text}")
    else:
        st.write("No major knowledge gaps detected.")

    st.subheader("Attention Score")
    attention_block = report.get("attention", {})
    st.metric("Score", f"{attention_block.get('score', 0.0):.2f}%")
    st.write(
        f"Face Visibility: {attention_block.get('visibility', 0.0):.2f}%  "
        f"Head Orientation: {attention_block.get('head_orientation', 0.0):.2f}%  "
        f"Eye Direction: {attention_block.get('eye_direction', 0.0):.2f}%  "
        f"Face Stability: {attention_block.get('stability', 0.0):.2f}%"
    )
    st.write(attention_block.get("explanation", ""))

    st.subheader("Speech Confidence")
    hesitation_block = report.get("hesitation", {})
    st.metric("Score", f"{hesitation_block.get('score', 0.0):.2f}%")
    st.write(
        f"Average Pause: {hesitation_block.get('average_pause', 0.0):.2f} sec  "
        f"Long Pauses: {hesitation_block.get('long_pauses', 0)}  "
        f"Words Per Minute: {hesitation_block.get('words_per_minute', 0.0):.2f}"
    )
    st.write(hesitation_block.get("explanation", ""))

    st.subheader("Emotion Analysis")
    emotion_block = report.get("emotion", {})
    dominant = emotion_block.get("dominant")
    if dominant:
        st.write(f"Dominant Emotion: {dominant}")
        if emotion_block.get("confidence") is not None:
            st.write(f"Confidence: {emotion_block.get('confidence')}%")
    else:
        st.write("Status:", emotion_block.get("status", "Unavailable"))
        if emotion_block.get("reason"):
            st.write("Reason:", emotion_block.get("reason"))
    if emotion_block.get("distribution"):
        st.write("Supporting Emotions:")
        for emotion, percent in emotion_block.get("distribution", {}).items():
            st.write(f"- {emotion}: {percent}%")

    st.subheader("Misconception Detection")
    if report.get("misconceptions"):
        for item in report.get("misconceptions", []):
            st.write(f"- {item.get('misconception')}")
            if item.get('correct_concept'):
                st.write(f"  Correct Concept: {item.get('correct_concept')}")
            st.write(f"  Reason: {item.get('reason')}")
    else:
        st.write("No misconceptions detected.")

    st.subheader("Explainable Feedback")
    st.write(report.get("feedback", ""))



os.makedirs("recordings", exist_ok=True)
os.makedirs("outputs", exist_ok=True)

if "topic" not in st.session_state:
    st.session_state.topic = ""
if "reference" not in st.session_state:
    st.session_state.reference = None
if "question" not in st.session_state:
    st.session_state.question = ""
if "status" not in st.session_state:
    st.session_state.status = ""
if "recording" not in st.session_state:
    st.session_state.recording = False
if "recording_started" not in st.session_state:
    st.session_state.recording_started = False
if "recording_finished" not in st.session_state:
    st.session_state.recording_finished = False
if "transcript" not in st.session_state:
    st.session_state.transcript = ""
if "timestamps" not in st.session_state:
    st.session_state.timestamps = []
if "semantic" not in st.session_state:
    st.session_state.semantic = None
if "concepts" not in st.session_state:
    st.session_state.concepts = None
if "misconceptions" not in st.session_state:
    st.session_state.misconceptions = None
if "attention" not in st.session_state:
    st.session_state.attention = None
if "emotion" not in st.session_state:
    st.session_state.emotion = None
if "hesitation" not in st.session_state:
    st.session_state.hesitation = None
if "auva" not in st.session_state:
    st.session_state.auva = None

with st.form(key="topic_form"):
    topic_input = st.text_input("Enter topic", value=st.session_state.topic)
    submit = st.form_submit_button("Explain Topic")

if submit:
    if not topic_input.strip():
        st.warning("Please enter a topic first.")
    else:
        tutor = AITutor()
        try:
            with st.spinner("Generating reference content..."):
                reference = tutor.generate_reference(topic_input.strip())
            st.session_state.topic = topic_input.strip()
            st.session_state.reference = reference
            st.session_state.question = ""
            st.session_state.status = "explanation"
            st.session_state.recording = False
            st.session_state.recording_started = False
            st.session_state.recording_finished = False
            st.session_state.transcript = ""
            st.session_state.timestamps = []
            st.success("Reference generated")
        except Exception as exc:
            st.error(f"Unable to generate reference: {exc}")

if st.session_state.reference is not None:
    st.header("Topic Explanation")
    st.write(st.session_state.reference.get("topic_explanation", ""))

    with st.expander("Reference diagnostics"):
        st.write(st.session_state.reference)
        st.write("Concepts:", st.session_state.reference.get("concepts"))
        st.write("Misconceptions:", st.session_state.reference.get("misconceptions"))
        st.write("Keywords:", st.session_state.reference.get("keywords"))
        if not st.session_state.reference.get("concepts"):
            st.warning("Reference concepts are missing or empty. Qwen output must include the expected concept list.")

    if st.button("Start Verification"):
        tutor = AITutor()
        try:
            with st.spinner("Generating verification question..."):
                question = tutor.generate_question(st.session_state.topic)
            st.session_state.question = question
            st.session_state.status = "verification"
            st.success("Verification question generated")
        except Exception as exc:
            st.error(f"Unable to generate question: {exc}")

if st.session_state.question:
    st.header("Verification Question")
    st.write(st.session_state.question)

    if not st.session_state.recording and not st.session_state.recording_finished:
        if st.button("Start Answering Session"):
            st.session_state.recording = True
            st.session_state.recording_started = False
            st.session_state.recording_finished = False

    if st.session_state.recording:
        countdown = st.empty()
        if not st.session_state.recording_started:
            for i in range(3, 0, -1):
                countdown.markdown(f"# {i}")
                time.sleep(1)
            countdown.markdown("# Recording Started")
            st.session_state.recording_started = True

        def create_recorder() -> MediaRecorder:
            return MediaRecorder(
                "recordings/student_answer.mp4",
                format="mp4",
                options={"movflags": "faststart"},
            )

        webrtc_ctx = webrtc_streamer(
            key="student",
            mode=WebRtcMode.SENDRECV,
            media_stream_constraints={
                "video": True,
                "audio": True,
            },
            in_recorder_factory=create_recorder,
        )

        st.success("Recording...")
        st.info("Explain your answer clearly.")
        st.warning("Click Finish Answer after completing.")

        if st.button("Finish Answer"):
            worker = webrtc_ctx._get_worker() if hasattr(webrtc_ctx, '_get_worker') else None
            if worker is not None:
                worker.stop()
            st.session_state.recording = False
            st.session_state.recording_started = False
            st.session_state.recording_finished = True
            st.success("Recording Completed")

    if st.session_state.recording_finished:
        if os.path.exists("recordings/student_answer.mp4"):
            st.success("Video Saved Successfully")
            st.info("Saved at recordings/student_answer.mp4")

            whisper = WhisperModel()
            with st.spinner("Transcribing student answer..."):
                try:
                    result = whisper.transcribe("recordings/student_answer.mp4")
                    st.session_state.transcript = result["transcript"]
                    st.session_state.timestamps = result["timestamps"]
                    whisper.save_outputs(st.session_state.transcript, st.session_state.timestamps)
                except Exception as exc:
                    st.error(f"Transcription failed: {exc}")
                    result = None

            if result is not None:
                # Run all analysis modules silently and display only the final report.
                semantic_result = verify.analyze_semantic(
                    st.session_state.reference["ideal_answer"],
                    st.session_state.transcript,
                )
                st.session_state.semantic = semantic_result

                concept_result = verify.analyze_concepts(
                    st.session_state.reference.get("concepts", []),
                    st.session_state.transcript,
                )
                st.session_state.concepts = concept_result

                misconception_result = verify.analyze_misconceptions(
                    st.session_state.transcript,
                    st.session_state.reference.get("misconceptions", []),
                    st.session_state.reference.get("ideal_answer", ""),
                )
                st.session_state.misconceptions = misconception_result

                if os.path.exists("recordings/student_answer.mp4"):
                    try:
                        runner = verify.run_unified_verification
                    except Exception:
                        # Fallback: import pipeline directly if attribute missing
                        from pipeline import VerificationPipeline

                        pipeline_res = VerificationPipeline().run(
                            st.session_state.reference,
                            "recordings/student_answer.mp4",
                            st.session_state.transcript,
                            st.session_state.timestamps,
                        )
                    else:
                        pipeline_res = runner(
                            st.session_state.reference,
                            "recordings/student_answer.mp4",
                            st.session_state.transcript,
                            st.session_state.timestamps,
                        )

                    auva_result = pipeline_res.get("auva", {})
                    report = pipeline_res.get("report", {})

                    attention_result = auva_result.get("attention", {})
                    emotion_result = auva_result.get("emotion", {})
                    hesitation_result = auva_result.get("hesitation", {})

                    st.session_state.attention = attention_result
                    st.session_state.emotion = emotion_result
                    st.session_state.hesitation = hesitation_result
                    st.session_state.auva = auva_result
                    st.session_state.semantic = {"score": auva_result.get("semantic", {}).get("average", 0.0)}
                    st.session_state.concepts = auva_result.get("concept", {})
                    st.session_state.misconceptions = auva_result.get("misconceptions", [])

                    if not auva_result:
                        st.warning("AUVA pipeline did not return a valid result. Check the pipeline output.")
                    else:
                        st.success("Verification complete.")
                        display_verification_report(report)



                st.subheader("Word Timestamps")
                for item in st.session_state.timestamps:
                    st.write(f"{item['word']} — {item['start']:.2f} to {item['end']:.2f}")
        else:
            st.warning("Recording finished, but the video file has not been saved yet.")
