class ReportGenerator:
    def __init__(self):
        pass

    def generate(
        self,
        transcript: str,
        semantic: dict,
        concept: dict,
        attention: dict,
        emotion: dict,
        hesitation: dict,
        misconception: list[dict],
        auva: dict,
    ) -> dict:
        detected_count = len(concept.get("detected", []))
        total_concepts = len(concept.get("detected", [])) + len(concept.get("missing", []))
        dominant_emotion = emotion.get("dominant")
        distribution = emotion.get("distribution", {})

        feedback = []
        if semantic.get("score", 0.0) > 85:
            feedback.append(
                "You explained the topic using concepts that are semantically close to the ideal answer."
            )
        if concept.get("coverage", 0.0) < 70:
            feedback.append("Some important concepts are missing.")
        if concept.get("missing"):
            feedback.append(
                f"You should revise: {', '.join(concept.get('missing', []))}."
            )
        if misconception:
            feedback.append(
                "Some misconceptions were detected. Review the highlighted incorrect explanations."
            )
        if hesitation.get("confidence", 0.0) < 70:
            feedback.append("Reduce long pauses by practising the explanation.")
        if attention.get("attention_score", 0.0) < 70:
            feedback.append("Maintain eye contact and focus during the explanation.")

        if not feedback:
            feedback.append(
                "You demonstrated strong understanding and delivery. Continue practicing to refine your confidence and concept coverage."
            )

        final_feedback = " ".join(feedback)

        report = {
            "transcript": transcript,
            "understanding_score": auva.get("understanding_score", 0.0),
            "performance": auva.get("performance", "Needs Improvement"),
            "auva_reasons": auva.get("reasons", []),
            "semantic": {
                "score": semantic.get("score", 0.0),
                "explanation": (
                    "The student's transcript and the ideal answer generated by Qwen were converted into semantic embeddings using SentenceTransformer. "
                    "Cosine similarity between these embeddings produced the semantic similarity score."
                ),
            },
            "concept": {
                "detected_count": detected_count,
                "total": total_concepts,
                "coverage": concept.get("coverage", 0.0),
                "detected": concept.get("detected", []),
                "missing": concept.get("missing", []),
                "explanation": (
                    "The concepts generated by Qwen were individually compared with the student's transcript. "
                    "Detected concepts contribute to the coverage score, while missing concepts indicate knowledge gaps."
                ),
            },
            "attention": {
                "score": attention.get("attention_score", 0.0),
                "visibility": attention.get("face_visibility", 0.0),
                "head_orientation": attention.get("head_score", 0.0),
                "eye_direction": attention.get("eye_score", 0.0),
                "stability": attention.get("stability", 0.0),
                "explanation": (
                    "Face visibility, head orientation, eye direction, and stability were combined into a single attention score. "
                    "This score reflects how engaged the student appeared during the explanation."
                ),
            },
            "emotion": {
                "dominant": dominant_emotion,
                "distribution": distribution,
                "analysis": emotion.get("analysis", "Emotion is detected using DeepFace and provides supporting evidence about confidence and engagement."),
                "explanation": (
                    "Emotion is detected using DeepFace and provides supporting evidence about confidence and engagement. "
                    "Emotions are supplementary and do not directly determine understanding."
                ),
            },
            "hesitation": {
                "score": hesitation.get("confidence", 0.0),
                "average_pause": hesitation.get("average_pause", 0.0),
                "long_pauses": hesitation.get("long_pauses", 0),
                "words_per_minute": hesitation.get("words_per_minute", 0.0),
                "explanation": (
                    "Average pause duration, long pauses, and speaking speed are used to calculate speech confidence. "
                    "Fewer and shorter pauses increase confidence, while long pauses indicate hesitation."
                ),
            },
            "misconceptions": misconception,
            "feedback": final_feedback,
        }

        return report
